In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
import tensorflow as tf
import numpy as np
import os, shutil


2022-08-01 11:46:23.835031: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-01 11:46:23.842250: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [4]:
%cd /home/guest/fruitfly/

/home/guest/fruitfly


In [5]:
class_names = ['attempt_copulate', 'following', 'licking', 'wing_song']

In [10]:
shutil.rmtree("./test/")
for i in class_names:
    os.makedirs(f'./test/{i}')

In [7]:
my_model = tf.keras.models.load_model("./best_model.h5")
def test_im(arr):
     # Convert single image to a batch.
    input_arr = np.expand_dims(arr, 0)
    predictions = my_model(input_arr, training=False)
    predictions = predictions.numpy()
    classes = np.argmax(predictions, axis = -1)
    print("===>>", class_names[classes[0]])
    print(predictions[0])
    return class_names[classes[0]], predictions[0][classes[0]]

2022-08-01 11:46:40.328219: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-08-01 11:46:40.328257: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-08-01 11:46:40.328288: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (guest-desktop): /proc/driver/nvidia/version does not exist


In [8]:
#Code to find the median frame and the absolute difference with the current frame
import numpy as np
import cv2
from math import ceil, floor
import random
from PIL import Image
import os
from glob import glob
import csv
from sys import exit

#padding to make all images equal square shape
desired_size = 80
def padd(arr, box):
    (x, y, w, h) = box
    extra_x = (desired_size-w)/2
    extra_y = (desired_size-h)/2
    extra_x1 = floor(extra_x)
    extra_x2 = ceil(extra_x)
    extra_y1 = floor(extra_y)
    extra_y2 = ceil(extra_y)
    new_im = orig[y1+y-extra_y1:y1+y+h+extra_y2, x1+x-extra_x1:x1+x+w+extra_x2]
    return new_im

video_fn = "./PC1Cam2__21919558__20220517_150136518.avi"
vs = cv2.VideoCapture(video_fn)
#get frames per second
fps = vs.get(cv2.CAP_PROP_FPS)

#calculate the median frame
###############################################################
med_list = []

for i in range(11):
    f_no = random.randint(1, vs.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f_no)
    vs.set(1, f_no)
    ret, frame = vs.read()
    fr = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    #fr = cv2.GaussianBlur(fr, (21, 21), 0)
    med_list.append(fr)
    
med_arr = np.array(med_list, dtype='uint8')
med_frame = np.median(med_arr, axis=0).astype('uint8')
med_frame = cv2.GaussianBlur(med_frame, (21, 21), 0)
################################################################

# use selectROIs to select only the wells
r =[]
cv2.namedWindow("Crop", cv2.WINDOW_NORMAL)
r = cv2.selectROIs("Crop", frame)
cv2.destroyWindow('Crop')

149
1109
1359
1842
1596
345
2324
1965
984
2136
955


In [12]:
dict_well = {0:'A', 1:'B', 2:'C', 3:'D'}
f = open('time_frames.csv', mode='w')
writer = csv.writer(f)

#vs.set(cv2.CAP_PROP_POS_FRAMES, 0)
vs = cv2.VideoCapture(video_fn)

#########iterate over each well############
for i in range(len(r)):   
    x1, y1, wid, hig = r[i]
    medCrop = med_frame[r[i][1]:r[i][1]+r[i][3], r[i][0]:r[i][0]+r[i][2]]
    name = dict_well[i]
    vs = cv2.VideoCapture(video_fn)
    while True:
        # grab the current frame     
        frame = vs.read()[1]
        # if the frame could not be grabbed, then we have reached the end
        # of the video
        if frame is None:
            break
            
        orig = frame.copy()

        frame_no = int(vs.get(cv2.CAP_PROP_POS_FRAMES)) 
        cur_sec = frame_no//fps
        cur_min = int(cur_sec//60), int(cur_sec%60)
        cur_min = str(cur_min[0])+':'+str(cur_min[1])
        
        frame = frame[r[i][1]:r[i][1]+r[i][3], r[i][0]:r[i][0]+r[i][2]]
        
        # convert it to grayscale, and blur it
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        gray = cv2.GaussianBlur(gray, (21, 21), 0)
    
        # compute the absolute difference between the current frame and
        # median frame
        frameDelta = cv2.absdiff(medCrop, gray)
        thresh = cv2.threshold(frameDelta, 35, 255, cv2.THRESH_BINARY)[1]
        # dilate the thresholded image to fill in holes, then find contours
        # on thresholded image
        thresh = cv2.dilate(thresh, None, iterations=3)
        
        cnts = cv2.findContours(thresh, cv2.RETR_EXTERNAL,
            cv2.CHAIN_APPROX_SIMPLE)[0]
        #sort the contours in the order of decreasing area
        cnts = sorted(cnts, key=cv2.contourArea, reverse=True)
        
        #masked = cv2.bitwise_and(frame,frame, mask=thresh)
        if len(cnts)==1 or cv2.contourArea(cnts[1])<.3*cv2.contourArea(cnts[0]):
            box = cv2.boundingRect(cnts[0])            
            cv2.rectangle(frame, (box[0], box[1]), (box[0] + box[2], box[1] + box[3]), (0, 255, 0), 2)
            padded = padd(frame, box)
            sub_class, pred_val = test_im(padded)
            if pred_val<0:
                continue
            cv2.putText(frame, 'well-'+name+': '+sub_class, (5, 15),\
               cv2.FONT_HERSHEY_SIMPLEX, 0.4 , (0,255,0))
            cv2.imwrite(f"./test/{sub_class}/Pos{name}_{int(cur_sec)}_{frame_no}.png", 
                    padded)
            if frame_no%fps == 0:
                writer.writerow(['well-'+name, cur_min, sub_class, pred_val])
        
    
        cv2.namedWindow("Security Feed", cv2.WINDOW_NORMAL)
        cv2.imshow("Security Feed",\
                   cv2.hconcat([frame, cv2.cvtColor(thresh, cv2.COLOR_GRAY2BGR)]))
        key = cv2.waitKey(1) & 0xFF
        # if the `q` key is pressed, break from the loop
        if key == ord("q") :
            break
        elif key == ord('p'):
            cv2.waitKey(0)
        elif key==27 :
            cv2.destroyAllWindows()
            exit(0)
    
# cleanup the camera and close any open windows
vs.release()
cv2.destroyAllWindows()
f.close()

===>> wing_song
[-2.4318085  0.5586605 -2.2161787  1.2073431]
===>> following
[-1.7923657  1.0196937 -2.0370808 -0.1521402]
===>> following
[-2.6215243   1.7807463  -2.5059783   0.63130623]
===>> following
[-1.6819626  1.0554849 -1.874337  -0.3351964]
===>> wing_song
[-2.9042284  -0.29879034 -0.9029214   2.3001103 ]
===>> following
[-2.7131524   0.99254787 -1.6918116   0.05257308]
===>> following
[-2.205107    0.12081868 -1.0933753  -0.27130488]
===>> following
[-2.5341766   0.5309775  -1.7233276   0.15495609]
===>> following
[-2.4393826  1.1379478 -2.3735409 -0.187436 ]
===>> following
[-3.0063698   0.98081356 -1.570067    0.83228934]
===>> wing_song
[-2.5551164  0.8600247 -2.1606336  1.0574012]
===>> following
[-1.7000493  1.7546949 -0.9984814 -1.4996867]
===>> following
[-1.5807728  1.8190283 -0.767075  -1.9224705]
===>> following
[-2.2222614  2.7299714 -1.9702162 -0.8658402]
===>> wing_song
[-3.2836485   0.61387175 -0.7655745   1.833511  ]
===>> wing_song
[-4.2762156  1.8457954 -2.

===>> attempt_copulate
[ 3.8119795  -3.2222679  -0.40908533 -4.705853  ]
===>> attempt_copulate
[ 1.828205   -2.0072386  -0.01904787 -4.3159    ]
===>> attempt_copulate
[ 0.00778521 -0.6791941  -0.30337474 -2.944099  ]
===>> attempt_copulate
[ 0.11834139 -0.7855588  -0.26459724 -2.7682838 ]
===>> following
[-0.8096145  -0.15790157 -0.65784    -1.8907083 ]
===>> following
[-1.7341709   0.16108604 -0.5370536  -0.9808206 ]
===>> following
[-0.1438486   0.8247548  -0.84375656 -3.3406425 ]
===>> following
[-0.7565605   0.44513962 -0.6136587  -1.7013111 ]
===>> attempt_copulate
[ 4.115018  -3.2940168  1.7184839 -6.8063936]
===>> attempt_copulate
[ 4.51146   -3.7556343  1.7602789 -6.6195726]
===>> attempt_copulate
[ 4.1574655 -3.9690905  2.147743  -6.30332  ]
===>> attempt_copulate
[ 4.275643  -4.457201   2.46804   -6.3965807]
===>> attempt_copulate
[ 4.333178  -4.5370345  1.8303986 -5.4499555]
===>> attempt_copulate
[ 4.4477262 -4.131544   1.5994625 -6.219886 ]
===>> attempt_copulate
[ 4.279

===>> licking
[-1.4487329 -2.5678883  0.8423504  0.6115779]
===>> attempt_copulate
[ 2.7012343 -4.994101   2.2693717 -3.6970308]
===>> attempt_copulate
[ 5.8087196 -6.3267274  1.8777106 -5.564472 ]
===>> attempt_copulate
[ 6.1634626 -6.121855   1.9030671 -6.387326 ]
===>> attempt_copulate
[ 5.8999987 -5.500397   1.0083303 -5.828061 ]
===>> attempt_copulate
[ 5.154152   -4.1617794  -0.02548017 -5.492932  ]
===>> attempt_copulate
[ 5.4614015  -4.408491   -0.30314508 -5.446491  ]
===>> attempt_copulate
[ 4.2129602 -3.4165645  0.1709507 -5.376376 ]
===>> attempt_copulate
[ 3.5349038  -2.8952968   0.25271645 -5.048958  ]
===>> attempt_copulate
[ 2.965215  -1.9715257 -0.3300901 -4.466609 ]
===>> attempt_copulate
[ 2.0443103  -1.6124457   0.50404805 -4.9597597 ]
===>> attempt_copulate
[ 1.3732245  -1.6038048   0.73177034 -4.0703506 ]
===>> attempt_copulate
[ 1.2035364 -1.8048079  1.1706864 -4.099815 ]
===>> attempt_copulate
[ 1.2528913 -1.7662333  1.1026025 -4.019174 ]
===>> attempt_copulate


===>> attempt_copulate
[ 5.9529    -5.3758245  1.4565157 -6.814425 ]
===>> attempt_copulate
[ 5.7323666 -5.286875   1.4183297 -6.4486604]
===>> attempt_copulate
[ 5.685469  -5.140198   1.5025151 -6.6456747]
===>> attempt_copulate
[ 5.387588  -4.994085   1.4694259 -6.164817 ]
===>> attempt_copulate
[ 5.621034  -5.088792   1.3876278 -6.512528 ]
===>> attempt_copulate
[ 5.474363  -5.0600176  1.4529073 -6.2954745]
===>> attempt_copulate
[ 5.531704  -4.8399177  1.7091    -7.066905 ]
===>> attempt_copulate
[ 5.1814322 -4.517871   2.010895  -7.158568 ]
===>> attempt_copulate
[ 5.193101  -4.4974275  1.6633826 -6.934234 ]
===>> attempt_copulate
[ 5.1413956 -4.5278287  1.7423315 -6.9308767]
===>> attempt_copulate
[ 5.086597  -4.415464   1.6570729 -6.8141155]
===>> attempt_copulate
[ 5.1548    -4.4450264  1.7814119 -7.0650206]
===>> attempt_copulate
[ 5.3345323 -4.3827877  1.5736932 -7.3529634]
===>> attempt_copulate
[ 5.350984  -4.4375553  1.6143702 -7.3802376]
===>> attempt_copulate
[ 5.3678513

===>> attempt_copulate
[ 4.736885   -3.4925508   0.57317716 -5.8292413 ]
===>> attempt_copulate
[ 4.7626495  -3.56197     0.56134313 -5.853786  ]
===>> attempt_copulate
[ 4.8141193  -3.5753908   0.59953094 -5.847459  ]
===>> attempt_copulate
[ 5.00683    -3.684487    0.57152367 -6.049569  ]
===>> attempt_copulate
[ 4.6926413  -3.5186064   0.44345087 -5.596763  ]
===>> attempt_copulate
[ 4.6128774  -3.550849    0.58059305 -5.792578  ]
===>> attempt_copulate
[ 4.558512  -3.532043   0.55331   -5.9942894]
===>> attempt_copulate
[ 2.1892223  -1.867029    0.27914146 -4.1802425 ]
===>> following
[-0.23613428  0.11150234 -0.6030976  -1.8244597 ]
===>> following
[-0.45747048  0.07555711 -0.4801614  -1.5234011 ]
===>> following
[-3.3407855  2.0525093 -1.5573336  0.6358623]
===>> licking
[-0.352472    0.02120094  0.5443249  -2.6197064 ]
===>> following
[-0.9845223   0.21088098  0.16764164 -1.4586232 ]
===>> licking
[-0.17209853 -0.01691061  0.46600598 -2.7204764 ]
===>> licking
[-0.36139432 -0.12

===>> attempt_copulate
[ 6.0829077  -4.558983   -0.14340372 -6.5103793 ]
===>> attempt_copulate
[ 5.417581  -4.3140235  0.1771915 -5.636073 ]
===>> attempt_copulate
[ 5.7617016  -4.7587028   0.40218776 -6.093349  ]
===>> attempt_copulate
[ 5.3963823  -4.2905803   0.14518079 -5.9722795 ]
===>> attempt_copulate
[ 3.7852104  -3.8148725   0.63199794 -4.780874  ]
===>> attempt_copulate
[ 3.0482     -3.2710488   0.28279015 -4.199144  ]
===>> attempt_copulate
[ 2.4822614 -2.834209   0.156014  -3.5136094]
===>> attempt_copulate
[ 1.508648   -2.3320735   0.42535338 -3.010781  ]
===>> attempt_copulate
[ 1.1266912  -2.0420256   0.10004694 -2.8071392 ]
===>> attempt_copulate
[ 1.2620187  -2.3158078   0.21071008 -2.898978  ]
===>> attempt_copulate
[ 1.0931664  -2.260636    0.04215812 -2.6624382 ]
===>> attempt_copulate
[ 1.2586727  -2.1871567   0.14074811 -2.8803253 ]
===>> attempt_copulate
[ 1.7237986  -2.457627    0.07590684 -3.2054958 ]
===>> attempt_copulate
[-0.22009501 -1.0166445  -0.3413899 

===>> attempt_copulate
[ 0.00899676 -0.9705323  -0.25415364 -2.3580194 ]
===>> attempt_copulate
[ 3.183912   -2.6377017  -0.57270366 -3.9467354 ]
===>> attempt_copulate
[ 2.7525487 -2.376891  -0.2558156 -4.0243497]
===>> attempt_copulate
[ 3.2088788  -2.3928804  -0.20725827 -5.1336975 ]
===>> attempt_copulate
[ 5.3665333 -4.572417   0.7539903 -6.476606 ]
===>> attempt_copulate
[ 5.7536855 -5.189675   1.0961677 -6.5953684]
===>> attempt_copulate
[ 5.820775  -5.0145407  0.8987708 -6.256446 ]
===>> attempt_copulate
[ 6.666854  -5.9784     1.2498784 -7.1900415]
===>> attempt_copulate
[ 6.7219434 -5.919299   1.1981103 -7.242973 ]
===>> attempt_copulate
[ 6.6041756 -6.0564013  1.2591882 -6.9672976]
===>> attempt_copulate
[ 6.543447 -6.224883  1.600239 -6.965346]
===>> attempt_copulate
[ 6.9017596 -6.6109934  1.6343665 -7.321533 ]
===>> attempt_copulate
[ 6.686377  -6.542869   1.7070215 -7.155131 ]
===>> attempt_copulate
[ 6.869893  -6.655235   1.5490365 -7.226318 ]
===>> attempt_copulate
[ 6

===>> attempt_copulate
[ 5.0990796 -3.7216678  0.9094872 -6.5650616]
===>> attempt_copulate
[ 5.2602706 -3.872008   0.7824742 -6.69613  ]
===>> attempt_copulate
[ 5.1511693 -3.6638892  0.6413806 -6.4836226]
===>> attempt_copulate
[ 4.93433    -3.4374425   0.33326334 -6.1993146 ]
===>> attempt_copulate
[ 4.35643    -3.1846168   0.52271765 -5.807576  ]
===>> attempt_copulate
[ 3.976221   -3.0071645   0.33122665 -5.1888127 ]
===>> attempt_copulate
[ 3.6469631  -2.8474038   0.43904695 -5.326802  ]
===>> attempt_copulate
[ 4.031329  -3.0333738  0.6024217 -5.895699 ]
===>> attempt_copulate
[ 4.0122075 -2.9830246  0.4665354 -5.7899895]
===>> attempt_copulate
[ 3.7406402  -2.7967968   0.35825214 -5.269289  ]
===>> attempt_copulate
[ 4.6249375  -3.3578298   0.61244243 -6.2072377 ]
===>> attempt_copulate
[ 4.37013    -3.1565917   0.34368137 -5.7894306 ]
===>> attempt_copulate
[ 3.1509712 -2.4686313  0.6459725 -5.3074746]
===>> attempt_copulate
[ 3.0737343  -2.3816187   0.59121627 -5.2946343 ]
==

===>> licking
[-0.77617687 -2.0749314   0.77304566 -0.9105459 ]
===>> licking
[-2.6680725 -1.5471221  1.0627526  1.008995 ]
===>> following
[-2.4859006   0.94156224 -0.9469572  -0.7027238 ]
===>> following
[-1.2195531  -0.04884513 -0.08552949 -1.5543673 ]
===>> attempt_copulate
[ 1.3198907 -1.7416643  0.2747618 -2.7710948]
===>> attempt_copulate
[ 0.41138726 -0.81227636 -0.49632433 -1.8990958 ]
===>> attempt_copulate
[ 3.0708675 -2.8700035  0.717361  -5.2354393]
===>> attempt_copulate
[ 6.083823  -5.215044   1.0747068 -6.929582 ]
===>> attempt_copulate
[ 6.456303  -6.4879823  1.6217009 -6.4890203]
===>> attempt_copulate
[ 6.6143208 -6.6050916  1.8647028 -6.930072 ]
===>> attempt_copulate
[ 5.1696925 -5.5961914  1.6910548 -5.3022604]
===>> attempt_copulate
[ 5.637963  -6.1944413  1.6636056 -5.1301603]
===>> attempt_copulate
[ 4.660971  -5.549022   1.6453252 -4.5656333]
===>> attempt_copulate
[ 2.3876863 -4.5277586  2.0836675 -3.3102355]
===>> licking
[ 2.2206492 -4.5302763  2.3336837 -3

===>> attempt_copulate
[ 2.2131474  -1.9428273   0.51609266 -4.582201  ]
===>> attempt_copulate
[ 2.3434782  -1.8124597   0.45905334 -4.864813  ]
===>> attempt_copulate
[ 2.540208  -2.0846283  0.5419476 -4.9237685]
===>> attempt_copulate
[ 2.5552661 -2.1592295  0.58663   -4.9987416]
===>> attempt_copulate
[ 2.6020348  -2.115185    0.53136444 -4.9964037 ]
===>> attempt_copulate
[ 2.4534554  -2.0716395   0.56315273 -4.8796444 ]
===>> attempt_copulate
[ 2.4541461  -2.020113    0.49870482 -4.797475  ]
===>> attempt_copulate
[ 2.1910982 -2.0590396  0.6365969 -4.5100007]
===>> attempt_copulate
[ 2.2678008 -2.0299158  0.5772523 -4.6050844]
===>> attempt_copulate
[ 2.2425337 -2.0326953  0.7134118 -4.6971946]
===>> attempt_copulate
[ 2.2493796 -2.075313   0.7245045 -4.674967 ]
===>> attempt_copulate
[ 2.2590714 -2.143652   0.6178733 -4.577091 ]
===>> attempt_copulate
[ 2.282684  -2.0584483  0.6226124 -4.603473 ]
===>> attempt_copulate
[ 2.2670836  -2.108487    0.63660735 -4.5955873 ]
===>> atte

===>> following
[-3.4154723  1.2324572 -2.2457058  0.659261 ]
===>> following
[-3.4332483  1.2735164 -2.2384772  0.6091223]
===>> following
[-3.0084596   1.230375   -2.3352952   0.56191033]
===>> following
[-3.0232852   1.3290162  -2.6279328   0.50422156]
===>> following
[-3.2368102   1.3160595  -2.453795    0.63554984]
===>> following
[-3.1827807   1.3582847  -2.5073054   0.62233514]
===>> following
[-2.8202264  0.9601166 -2.0967534 -0.0971206]
===>> following
[-2.7167134   0.74747735 -1.8868325  -0.3159752 ]
===>> licking
[-1.6602387  -0.5537996   0.10436464 -2.059596  ]
===>> attempt_copulate
[ 3.106626  -2.5994256 -0.8524988 -4.5073247]
===>> attempt_copulate
[ 3.7403066  -3.1965237  -0.47440538 -5.183989  ]
===>> attempt_copulate
[ 4.5352817 -3.4698815 -0.64852   -5.7072406]
===>> attempt_copulate
[ 4.5031986  -3.4846668  -0.54896367 -5.593564  ]
===>> attempt_copulate
[ 4.044712   -3.2689967  -0.58859783 -5.3818836 ]
===>> attempt_copulate
[ 3.761936  -3.041842  -0.5087511 -5.329

===>> following
[-1.909978   1.1888083 -2.8108013  0.6214611]
===>> following
[-1.7451952   0.9923629  -2.6945257   0.52243775]
===>> following
[-1.9258515   1.030117   -2.7465782   0.73880494]
===>> following
[-2.569138   1.4234148 -2.9460585  1.292343 ]
===>> following
[-2.2284377  1.2630715 -2.999202   1.1506848]
===>> following
[-1.9401687  0.9683984 -2.3770452  0.5391284]
===>> following
[-2.0245333   1.1448352  -2.2787242   0.41073912]
===>> following
[-1.5000132   0.89746803 -2.617505    0.42735058]
===>> following
[-1.2418693   0.88273895 -2.1623201  -0.8485897 ]
===>> following
[-0.4519134  -0.04015924 -1.3142606  -1.8166738 ]
===>> attempt_copulate
[-0.1392076  -0.29926264 -0.9242855  -2.8288445 ]
===>> attempt_copulate
[ 0.11436018 -0.5102387  -1.2378498  -2.156182  ]
===>> following
[-1.030372    0.36614123 -1.8545438  -0.71206087]
===>> following
[-1.168748   0.5532691 -1.8583748 -0.9553029]
===>> following
[-1.0394607   0.21545768 -1.8668653  -0.94225115]
===>> following


===>> attempt_copulate
[ 3.783176   -3.1988275  -0.29126853 -4.9125094 ]
===>> attempt_copulate
[ 2.4556577 -1.777872  -0.529774  -4.819677 ]
===>> attempt_copulate
[ 0.9402653  -0.29758564 -1.2982832  -3.8149128 ]
===>> attempt_copulate
[ 1.1578766  -0.47610316 -1.2298144  -4.0786815 ]
===>> attempt_copulate
[ 1.0557121  -0.23376328 -1.445227   -3.9193184 ]
===>> attempt_copulate
[ 1.3428259 -0.620936  -1.2087634 -4.1989074]
===>> attempt_copulate
[ 1.9296112 -1.0929064 -1.090027  -4.335319 ]
===>> attempt_copulate
[ 1.6135043  -0.76610565 -1.322647   -3.8802056 ]
===>> attempt_copulate
[ 1.5499144  -0.94210756 -1.1651677  -3.5798538 ]
===>> attempt_copulate
[ 1.4921045 -0.8568135 -1.210938  -3.561566 ]
===>> attempt_copulate
[ 1.3758243  -0.64985013 -1.2831783  -3.5568464 ]
===>> attempt_copulate
[ 1.5295603  -1.0727096  -0.97359216 -3.6541023 ]
===>> attempt_copulate
[ 1.119942   -0.75603384 -0.66036254 -3.7518923 ]
===>> following
[-0.19968349  0.04730988 -0.6411808  -2.6402206 ]
=

===>> attempt_copulate
[ 4.890936   -3.9786253  -0.49142644 -6.117243  ]
===>> attempt_copulate
[ 5.084921  -3.873414  -0.6138071 -6.3130198]
===>> attempt_copulate
[ 5.019761   -3.7841072  -0.57668734 -6.2762876 ]
===>> attempt_copulate
[ 5.298356   -4.0912642  -0.47979847 -6.2787337 ]
===>> attempt_copulate
[ 5.443023   -4.1713643  -0.45490655 -6.556839  ]
===>> attempt_copulate
[ 5.443503  -4.12817   -0.4937484 -6.5940537]
===>> attempt_copulate
[ 5.0660067 -3.7516572 -0.7127143 -6.236949 ]
===>> attempt_copulate
[ 5.162425   -3.820492   -0.62222296 -6.471463  ]
===>> attempt_copulate
[ 5.1218357 -3.8041606 -0.5749263 -6.343497 ]
===>> attempt_copulate
[ 5.1199355  -3.8355403  -0.60020006 -6.445626  ]
===>> attempt_copulate
[ 4.23473   -3.0767214 -1.0074308 -5.4111667]
===>> attempt_copulate
[ 2.0707557 -2.1700249 -0.7087959 -3.9488645]
===>> attempt_copulate
[ 1.1933367 -1.6788659 -0.4336877 -4.1571317]
===>> attempt_copulate
[ 0.9637302  -1.2690783  -0.65073895 -3.956882  ]
===>> 

===>> following
[-1.9363087   0.5572246  -0.41263223 -0.40275183]
===>> following
[-2.1591651   0.6968117  -0.46536037 -0.30915707]
===>> following
[-2.1439075   0.5510793  -0.41050512 -0.27082786]
===>> following
[-1.9160794   0.5224278  -0.38151032 -0.4506692 ]
===>> following
[-1.8044368   0.6674336  -0.6347383  -0.40165514]
===>> following
[-1.7754526   0.68939805 -0.65376437 -0.35967964]
===>> following
[-1.9252772   0.7468607  -0.6894603  -0.25293902]
===>> following
[-1.746265    0.6355664  -0.70528734 -0.39841157]
===>> following
[-1.7461153   0.61619306 -0.5288639  -0.5041913 ]
===>> following
[-1.6864834   0.61366093 -0.5576578  -0.48440295]
===>> following
[-1.794406    0.64673334 -0.5242586  -0.46399456]
===>> following
[-1.7507507   0.6841317  -0.54650337 -0.45274517]
===>> following
[-1.6704342   0.63542515 -0.57658285 -0.5001765 ]
===>> following
[-1.7788997   0.6025611  -0.56077737 -0.41260916]
===>> following
[-1.6772774   0.56981605 -0.5283799  -0.51503193]
===>> foll

===>> following
[-1.8516309   0.36237854 -1.5414444   0.19475558]
===>> following
[-1.819837    0.3778397  -1.532122    0.14580004]
===>> following
[-1.7948036   0.33675015 -1.5481179   0.03137798]
===>> following
[-1.8340145   0.36245078 -1.6990234   0.25117144]
===>> following
[-1.9723997   0.5077482  -1.6772898   0.20612675]
===>> following
[-1.7788124   0.39609903 -1.5940596   0.10041771]
===>> following
[-1.9529762   0.39846042 -1.6803347   0.1950235 ]
===>> following
[-1.8994316  0.4385662 -1.6230292  0.2172744]
===>> following
[-1.8672888   0.4116317  -1.6483463   0.24117732]
===>> following
[-1.9881637   0.50025636 -1.6654208   0.17351434]
===>> following
[-1.9442384   0.5013786  -1.7557962   0.27960628]
===>> following
[-1.8651053   0.4382606  -1.576296    0.13227502]
===>> following
[-1.9928184   0.49809158 -1.6364089   0.21465161]
===>> following
[-1.7573873   0.39056793 -1.7197297   0.23291074]
===>> following
[-1.9651028   0.557202   -1.6813996   0.24484505]
===>> followin

===>> following
[-1.6208289   0.43878835 -1.6307964   0.11240674]
===>> following
[-1.5807463   0.3886208  -1.4835371   0.05196593]
===>> following
[-1.776997    0.57928747 -1.5717926   0.05083174]
===>> following
[-1.758328    0.5230189  -1.5898483   0.14498432]
===>> following
[-1.596187    0.3902011  -1.5596731   0.14855525]
===>> following
[-1.784455    0.47600207 -1.5765762   0.11102091]
===>> following
[-1.7540516   0.6070957  -1.5510523  -0.00511611]
===>> following
[-1.6345012   0.44683355 -1.5628891   0.11772934]
===>> following
[-1.5961779   0.39200774 -1.5138428   0.12389655]
===>> following
[-1.7390774   0.5825567  -1.5801646   0.01423128]
===>> following
[-1.5739896   0.34424487 -1.5363909   0.07314651]
===>> following
[-1.7105837   0.5136743  -1.5438522   0.08225788]
===>> following
[-1.7961012   0.48673823 -1.5849162   0.16938981]
===>> following
[-1.6801255   0.46854517 -1.5067154   0.14372036]
===>> following
[-1.6955862   0.427109   -1.5339614   0.14186168]
===>> foll

===>> following
[-1.6973622   0.4582963  -1.5462822   0.21431597]
===>> following
[-1.7463268   0.40117452 -1.55096     0.2126272 ]
===>> following
[-1.6010971   0.40413913 -1.5814044   0.11031909]
===>> following
[-1.9758542   0.5169659  -1.5108432   0.19721244]
===>> following
[-1.1378057  -0.25771892 -1.1207154  -0.3842978 ]
===>> attempt_copulate
[-0.18644452 -0.90658915 -0.5860426  -0.9987818 ]
===>> attempt_copulate
[ 4.586763   -4.2851386   0.36515296 -4.8830976 ]
===>> attempt_copulate
[ 5.6566515 -5.231487   1.2165548 -6.411112 ]
===>> attempt_copulate
[ 5.453308  -5.426867   2.0484326 -6.3187633]
===>> attempt_copulate
[ 5.3363028 -5.570027   2.1065338 -5.953893 ]
===>> attempt_copulate
[ 4.800137  -5.0896645  2.4506705 -5.80665  ]
===>> attempt_copulate
[ 5.163858  -5.6021714  2.6752312 -6.189814 ]
===>> attempt_copulate
[ 5.009392  -5.3533487  2.5450182 -6.040108 ]
===>> attempt_copulate
[ 4.705071  -5.1939116  2.3649454 -5.493882 ]
===>> attempt_copulate
[ 5.0185633 -5.358

===>> licking
[-0.53591365 -2.2802322   0.51156247 -0.4812141 ]
===>> licking
[-1.0392332  -2.189405    0.42404562 -0.12226743]
===>> licking
[-0.4054914 -0.5769791  0.3513999 -1.6851625]
===>> attempt_copulate
[ 3.9405315 -3.3429806  0.9060842 -5.3643465]
===>> attempt_copulate
[ 3.9228785 -3.1290028  0.8908953 -5.3660197]
===>> attempt_copulate
[ 3.7531865 -2.7780204  0.7866254 -5.0912256]
===>> attempt_copulate
[ 3.6381314 -3.1392984  1.0135858 -5.3116045]
===>> attempt_copulate
[ 4.2947364 -3.7656033  1.1889045 -6.2645016]
===>> attempt_copulate
[ 3.3898811 -2.9685283  0.8425351 -5.1401925]
===>> attempt_copulate
[ 3.7133503 -3.263005   0.9711734 -5.8457446]
===>> attempt_copulate
[ 3.1185873 -2.9486296  0.8817635 -5.416922 ]
===>> attempt_copulate
[ 3.5313158 -3.3197072  0.9965617 -6.1010175]
===>> attempt_copulate
[ 4.1481595 -3.8237164  1.1725049 -6.562682 ]
===>> attempt_copulate
[ 2.859276  -2.5909352  0.6566717 -5.2753882]
===>> attempt_copulate
[ 3.6553986 -3.2923026  0.7741

===>> attempt_copulate
[ 5.2759686  -4.1219854   0.15041249 -5.377642  ]
===>> attempt_copulate
[ 4.6822734  -3.190615   -0.20930226 -5.163315  ]
===>> attempt_copulate
[ 4.1930704  -2.680195   -0.43391564 -4.933314  ]
===>> attempt_copulate
[ 2.5787253 -1.7807361 -0.6831998 -3.6716788]
===>> attempt_copulate
[ 1.7717437 -1.5606714 -0.5343449 -2.957918 ]
===>> attempt_copulate
[ 2.013863  -1.7546344 -0.3283641 -3.3813298]
===>> attempt_copulate
[ 3.1874053  -2.2574985  -0.21767803 -4.615653  ]
===>> attempt_copulate
[ 5.363051  -3.5238972 -0.7810985 -5.366729 ]
===>> attempt_copulate
[ 5.7075305 -3.5214589 -1.276419  -5.39085  ]
===>> attempt_copulate
[ 5.742354  -3.6770937 -1.00308   -5.3137407]
===>> attempt_copulate
[ 5.6912994  -4.1210475  -0.14595298 -5.6675286 ]
===>> attempt_copulate
[ 5.5588155 -4.041941  -0.1378701 -5.529922 ]
===>> attempt_copulate
[ 5.5248303  -3.934657   -0.17157951 -5.4715853 ]
===>> attempt_copulate
[ 5.0814176  -3.6556013   0.00761356 -5.51914   ]
===>> 

===>> attempt_copulate
[ 3.957721  -4.8454075  1.4648432 -4.0283732]
===>> attempt_copulate
[ 2.697982  -4.4502754  1.895725  -3.1973093]
===>> attempt_copulate
[ 2.1087673 -3.971851   1.6966482 -2.6682513]
===>> licking
[ 1.7288668 -3.732028   1.8521808 -2.5344656]
===>> attempt_copulate
[ 1.901924  -3.85673    1.7941828 -2.691294 ]
===>> attempt_copulate
[ 2.0484538 -3.9794083  1.8048483 -2.7562141]
===>> attempt_copulate
[ 2.1527753 -4.0342493  1.7873745 -2.837566 ]
===>> licking
[ 1.4675341 -4.08202    2.3550127 -2.5315096]
===>> licking
[-0.9968907  -2.6548395   2.209945   -0.47034317]
===>> licking
[-2.6094496 -1.808245   1.4307191  1.3335048]
===>> following
[-1.0048214   0.38880125 -1.4725115  -1.3074517 ]
===>> following
[-0.05490984  0.08403653 -1.245569   -2.6467829 ]
===>> attempt_copulate
[ 0.65545857 -0.38498113 -0.933826   -3.291082  ]
===>> following
[-0.5188894   0.32563245 -1.209832   -2.262152  ]
===>> following
[-0.0339107   0.38628215 -1.2055255  -2.484948  ]
===>>

===>> following
[-2.4389367   1.5822484  -1.3047377  -0.11995096]
===>> following
[-2.0633626   1.480578   -1.3932335  -0.05039782]
===>> following
[-1.6595446   1.1173307  -1.2064621   0.05609927]
===>> following
[-0.9489855   0.6412423  -0.77751106 -0.9611929 ]
===>> following
[-0.97748536  0.6875025  -0.9294328  -0.7811454 ]
===>> following
[-0.95077723  0.5645827  -0.7640082  -0.87055904]
===>> following
[-1.1299219   0.64140004 -0.8039714  -0.6980665 ]
===>> following
[-1.0832744   0.86397207 -1.0009557  -0.6746918 ]
===>> following
[-1.2534854   0.7941923  -0.73136127 -0.719383  ]
===>> following
[-1.1151522  0.739312  -0.8730743 -0.6409191]
===>> following
[-1.0483427   0.73885834 -0.8123866  -0.7885304 ]
===>> following
[-1.141434    0.71172136 -0.72232217 -0.7108587 ]
===>> following
[-1.0480944   0.63432986 -0.6281913  -0.8960168 ]
===>> following
[-0.7400019   0.3353337  -0.49049813 -1.2132862 ]
===>> following
[-0.51282007  0.28422952 -0.61366516 -1.1854879 ]
===>> followin

===>> attempt_copulate
[ 5.205736  -3.7365372  0.5616124 -6.5922985]
===>> attempt_copulate
[ 5.2616887  -3.6653204   0.83686256 -6.869722  ]
===>> attempt_copulate
[ 5.601689   -4.007128    0.49846932 -6.9431844 ]
===>> attempt_copulate
[ 5.637225   -3.983142    0.47563365 -6.917816  ]
===>> attempt_copulate
[ 5.522165   -3.86211     0.56473184 -6.919672  ]
===>> attempt_copulate
[ 5.223437   -3.6203988   0.47890028 -6.490722  ]
===>> attempt_copulate
[ 5.2898574 -3.7018352  0.5529364 -6.6070642]
===>> attempt_copulate
[ 5.3791156  -3.7370503   0.43719557 -6.623567  ]
===>> attempt_copulate
[ 5.154233  -3.633044   0.5309572 -6.4736333]
===>> attempt_copulate
[ 5.1776104 -3.6466844  0.4706197 -6.4539204]
===>> attempt_copulate
[ 4.6815853  -3.5444558   0.35759068 -5.652363  ]
===>> attempt_copulate
[ 5.0380855 -3.6115973  0.6277915 -6.394676 ]
===>> attempt_copulate
[ 4.5797405 -3.470454   0.3749029 -5.562932 ]
===>> attempt_copulate
[ 4.511206   -3.2642124   0.02652804 -5.244233  ]
==

===>> following
[-1.7414484   1.2076864  -0.15704744 -1.3017825 ]
===>> following
[-1.2587337   1.2728926  -0.51099056 -1.5888709 ]
===>> following
[-0.9243327   1.2425307  -0.71480125 -1.7918694 ]
===>> attempt_copulate
[ 1.1855367 -1.3591188  1.1434166 -3.8416657]
===>> attempt_copulate
[ 4.04111   -3.0225585  1.3765976 -6.2420225]
===>> attempt_copulate
[ 3.8304672 -3.3824158  1.9027125 -5.554917 ]
===>> attempt_copulate
[ 4.5594816 -3.687045   2.022769  -6.4377103]
===>> attempt_copulate
[ 4.9283137 -3.913771   2.0565944 -7.0088353]
===>> attempt_copulate
[ 4.873619  -3.929825   2.0981412 -6.981592 ]
===>> attempt_copulate
[ 4.3263297 -3.0676324  1.7247969 -6.9342527]
===>> attempt_copulate
[ 3.5124183 -2.6411204  1.3178958 -5.828572 ]
===>> attempt_copulate
[ 2.063259  -2.106915   1.1476982 -4.0549035]
===>> attempt_copulate
[ 1.2696321 -1.7626059  1.2139928 -3.416052 ]
===>> licking
[ 1.3026224 -1.8183692  1.3157139 -3.5214908]
===>> licking
[ 1.2335746 -1.9207455  1.3697003 -3.3

===>> attempt_copulate
[ 0.42815313 -1.117215    0.04946104 -1.7410489 ]
===>> attempt_copulate
[ 0.27677432 -0.6824307  -0.14566003 -1.7347716 ]
===>> attempt_copulate
[ 0.3449797  -0.6092382  -0.34153235 -1.6195985 ]
===>> attempt_copulate
[ 0.22409128 -0.5297308  -0.37906742 -1.4812151 ]
===>> attempt_copulate
[-0.04248982 -0.30108884 -0.43254742 -1.3306803 ]
===>> attempt_copulate
[-0.08150233 -0.2740584  -0.3628662  -1.3780376 ]
===>> attempt_copulate
[ 0.3222244  -0.79995304 -0.13623075 -1.700631  ]
===>> attempt_copulate
[ 0.1390241 -0.2714452 -0.4597817 -1.8066963]
===>> attempt_copulate
[ 0.07344139 -0.12030108 -0.4997631  -1.8806741 ]
===>> attempt_copulate
[ 0.5361018 -0.6531766 -0.5812962 -1.6921234]
===>> attempt_copulate
[ 0.94410473 -0.9887029  -0.48440823 -1.942974  ]
===>> attempt_copulate
[ 0.9668949  -0.87135893 -0.7229456  -1.9739028 ]
===>> attempt_copulate
[ 1.0045124  -0.83410335 -0.72612256 -1.8703654 ]
===>> attempt_copulate
[ 1.0008157 -0.768575  -0.8222123 -1

===>> wing_song
[-1.4528018  -0.61584663 -0.66814744  0.31960863]
===>> attempt_copulate
[ 0.34710547 -1.2033616  -0.3025942  -2.3395894 ]
===>> attempt_copulate
[ 4.0796824  -3.5455499   0.63790464 -5.7531486 ]
===>> attempt_copulate
[ 5.486589  -4.642107   0.7104364 -6.129568 ]
===>> attempt_copulate
[ 5.1555295 -4.9013906  1.4967644 -5.7044544]
===>> attempt_copulate
[ 5.240461  -5.378823   1.7181519 -5.717997 ]
===>> attempt_copulate
[ 5.566941  -4.8126535  0.8011209 -5.9603863]
===>> attempt_copulate
[ 6.183184  -4.7491455 -0.0315783 -6.408308 ]
===>> attempt_copulate
[ 6.157228   -4.7253222  -0.19797073 -6.26909   ]
===>> attempt_copulate
[ 5.623971   -4.109063   -0.08747739 -5.9077044 ]
===>> attempt_copulate
[ 4.3023143  -3.1761942  -0.56314874 -4.815864  ]
===>> attempt_copulate
[ 3.3009799  -2.4376025  -0.71519077 -4.403171  ]
===>> attempt_copulate
[ 2.4822772 -2.097549  -0.5259857 -4.0629563]
===>> attempt_copulate
[ 1.9173079  -1.658794   -0.74387395 -3.6404104 ]
===>> att

In [13]:
for fln in os.listdir('Cutouts/'):
    sub_class, pred_val = test_im(os.path.join("Cutouts/", fln))
    if pred_val<0:
        continue
    shutil.copy(os.path.join("Cutouts/", fln), f'test/{sub_class}')
    break

1/1 [==============================] - 0s 140ms/step
Cutouts/Crpp_14768_0.png ===>> wing_song
[-3.3914218  -0.15914679 -2.0753925   2.586185  ]
(1, 80, 80, 3)
